package com.example.demoConsumer.repository;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

@Getter
@Setter
@EqualsAndHashCode
@DynamoDBTable(tableName = "viacep")
public class ViacepEntity implements Serializable {

    private static final long serialVersionUID = 6940779301139204069L;
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @EqualsAndHashCode.Include
    private String id;
    @DynamoDBAttribute
    private String cep;
    @DynamoDBAttribute
    private String logradouro;
    @DynamoDBAttribute
    private String complemento;
    @DynamoDBAttribute
    private String bairro;
    @DynamoDBAttribute
    private String cidade;
    @DynamoDBAttribute
    private String estado;
    @DynamoDBAttribute
    private String ibge;
    @DynamoDBAttribute
    private String gia;
    @DynamoDBAttribute
    private String ddd;
    @DynamoDBAttribute
    private String siafi;
}
